[latest]
title = "테크M ─ 전체기사"
url = "https://www.techm.kr/news/articleList.html"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[contents]
title = "테크M ─ 콘텐츠"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN1&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[infrastructure]
title = "테크M ─ 인프라"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN2&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[innovation]
title = "테크M ─ 이노베이션"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN3&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[investment]
title = "테크M ─ 인베스트먼트"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN4&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[people]
title = "테크M ─ 피플"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN5&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[life]
title = "테크M ─ 라이프"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN6&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[report]
title = "테크M ─ 리포트"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN7&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"

[watching-news]
title = "테크M ─ 보는 뉴스"
url = "https://www.techm.kr/news/articleList.html?sc_serial_code=SRN10&view_type=sm"
entrySelector = "ul.type4 li.items"
titleSelector = "h4.titles a"
linkSelector = "a.thumb"
dateSelector = "span.byline em:nth-child(1)"
dateFormat = "yyyy.MM.dd hh:mm"
contentSelector = "span.byline em:nth-child(2)"
imageSelector = "a.thumb img"
waitUntil = "networkidle"